### ISSUE TITLE
Exploratory Data Analysis

### ISSUE THREAD

**Issue by venilv912** [MSTC-DA-IICT/Hacktoberfest23-Delve-into-ML#1]
## Objective
The objective of this issue is to Visualize the data, and provide the conclusions after each process, identify the patterns among the data which can help in improving our model, suggest what feature engineering can be done.

## Tasks
- Data Visualization, provide as much graphs as possible, and also provide conclusions after each process.
- Identify the patterns among the data.
- Conduct statistical analysis on the dataset to uncover relationships between variables.
- Suggest what feature engineering can be done on the data.

### The code should be well commented explaining the reason behind steps where necessary.

**Comment by ykodwani01** [comment]
Can I work on this issue?

**Comment by venilv912** [comment]
@ykodwani01 Yes, you can work on this issue.

**Comment by havkerboi123** [comment]
Is it still not done , can I work on this-?
